### ISSUE TITLE
visualize

### ISSUE THREAD

**Issue by RuiGangzai** [BUAABIGSCity/KDDCUP2022#1]
Hi @aptx1231 , how to visualize the results of wind power forecasting？I hope you can take some time out of your busy schedule to reply to this question, preferably with the code, thank you very much, it's really important to me!

**Comment by aptx1231** [comment]
Sorry for the late reply, your @ doesn't seem to have taken effect.

Visualizing the predicted results is just a matter of saving the results of this line of code:
`predictions = predict(settings, data_mean, data_scale, graph)  # (N,T,1)` in predict.py.

The output of this code is the prediction value, which is an array of shape(N,T,1) representing the prediction results for N positions at T time steps. Save it (np.save), and then use matplotlib to plot it (plt.plot(x,y)).
