### ISSUE TITLE
data Z-score normalization

### ISSUE THREAD

**Issue by hexuwei-epri** [BUAABIGSCity/KDDCUP2022#2]
hi @aptx1231 : 
In wpf_dataset.py, why are the mean and variance of node features calculated for all features of the node rather than for each feature of the node

self.data_mean = np.expand_dims( # (1, 134, 1, 1)

np.mean(

data[:, border1s[0]:border2s[0], 2:],

axis=(1, 2),

keepdims=True),

0)

self.data_scale = np.expand_dims( # (1, 134, 1, 1)

np.std(data[:, border1s[0]:border2s[0], 2:],

axis=(1, 2),

keepdims=True),

0)

**Comment by aptx1231** [comment]
Both methods were tried, but it was found that all the features together for the mean-variance worked better.

**Comment by hexuwei-epri** [comment]
@aptx1231 thank you for your help
